### ISSUE TITLE
Some system components are not displayed in the system language

### ISSUE THREAD

**Issue by ivanmood0** [G-dH/custom-hot-corners#1]
First of all, I want to thank you for a great extension, but there is one problem, after turning it on, some components of the system are displayed not only in the main system language (Ukrainian), but also in English.
Ubuntu 20.04.
Gnome 3.36
![lang_bug](https://user-images.githubusercontent.com/79835684/115623858-6c780880-a302-11eb-8963-5defb3bbfa6d.png)

**Comment by G-dH** [comment]
Hi, are you sure it is related to this extension? I have no idea how it could happen..

**Comment by ivanmood0** [comment]
> Hi, are you sure it is related to this extension? I have no idea how it could happen..

Yes, I'm sure. Earlier, I encountered this problem in other extensions, most recently in the extension "Extensions & Tweaks in system menu" and there, as the developer wrote, the problem was the conflict of other languages with German. I can't say anything about other cases, as information about the cause itself was not specified, for example in the "Night Light Slider" extension, here is a link to the problem number: https://codeberg.org/kiyui/gnome-shell-night-light-slider-extension/issues/83

**Comment by G-dH** [comment]
Thank you very much, for the bug report and links. As I don't use my system in my native language I didn't notice the issue before, but now I see it too, it's language independent, it just breaks translations. I was messing with gettext some time ago and eventually get it work for the extension, but ...
I uploaded the fix in `settings.js` file, just replace the one in `~/.local/share/gnome-shell/extensions/custom-hot-corners-extended@G-dH.github.com` and restart Shell. I will send it to EOG soon.

**Comment by ivanmood0** [comment]
> Thank you very much, for the bug report and links. As I don't use my system in my native language I didn't notice the issue before, but now I see it too, it's language independent, it just breaks translations. I was messing with gettext some time ago and eventually get it work for the extension, but ...
> I uploaded the fix in `settings.js` file, just replace the one in `~/.local/share/gnome-shell/extensions/custom-hot-corners-extended@G-dH.github.com` and restart Shell. I will send it to EOG soon.

Confirms that this fix fixes the language issue, but now there is another issue with non-working hot corners when you hover the mouse over them (when setting up left-click, they work, other options I did not check).

**Comment by G-dH** [comment]
Sorry, I've made a change in barrier size settings (split to horizontal and vertical) so now you don't have barrier size... I sent it to EGO already, you can try to download [zip here](https://extensions.gnome.org/review/download/24090.shell-extension.zip), or just wait for normal update.

**Comment by G-dH** [comment]
It's on extensions.gnome.org already available.
