### ISSUE TITLE
does not work in Fedora 34

### ISSUE THREAD

**Issue by Durlyn** [G-dH/custom-hot-corners#6]
does not work in Fedora 34. Say "ERROR". although, the parameters window opens

**Comment by G-dH** [comment]
It says ERROR after every bigger update, Shell needs to be restarted and Gnome page reloded...

**Comment by Durlyn** [comment]
the problem is something else. the error persists.

**Comment by G-dH** [comment]
Wayland or X11? Show me the output from this command, please:
`journalctl /usr/bin/gnome-shell --since "2 days ago" | grep corners-extended`

**Comment by Durlyn** [comment]
after today's update the gnome, everything worked. Thank you.
